version: "3"

volumes:
  postgres_data: {}

services:
  api:
    image: bitsb
    container_name: bitsb_api
    build:
      dockerfile: ./Dockerfile
      context: .
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  db:
    image: postgres:14
    container_name: bitsb_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitsb
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z