version: "3.8"

volumes:
  postgres_data: {}

services:
  api:
    image: bitsb
    container_name: bitsb_api
    build:
      dockerfile: ./deployments/Dockerfile
      context: ./
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env
    environment:
      - DB_DSN=postgres://postgres:postgres@db:5432/bitsb?sslmode=disable
      - WEBSITE_PORT=9090

  db:
    image: postgres:14
    container_name: bitsb_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bitsb
    healthcheck:
      test: pg_isready -U postgres
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true